// Generated by CoffeeScript 1.3.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

window.Page = (function() {

  Page.name = 'Page';

  function Page() {
    this.update = __bind(this.update, this);
    this.demo = ko.observable(new AttractionDemo());
    this.demo().init();
  }

  Page.prototype.update = function() {
    var particle, _i, _len, _ref, _results;
    requestAnimationFrame(this.update);
    this.demo().step();
    _ref = this.demo().physics.particles;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      particle = _ref[_i];
      particle.x(particle.pos.x);
      _results.push(particle.y(particle.pos.y));
    }
    return _results;
  };

  return Page;

})();
