// Generated by CoffeeScript 1.3.1
/* Integrator
*/

var Integrator;

Integrator = (function() {

  Integrator.name = 'Integrator';

  function Integrator() {}

  Integrator.prototype.integrate = function(particles, dt) {};

  return Integrator;

})();
